version: '3.9'

services:
  maven-build:
    image: maven:3.9
    container_name: maven-build-container_test
    volumes:
      - .:/app
    working_dir: /app
    command: [ "mvn", "clean", "install" ]
  
  spring-docker:
    image: openjdk:17
    container_name: spring-docker-container
    volumes:
      - ./target:/app
    ports:
      - 8080:8080
    command: ["java", "-jar", "/app/t1consulting_test_task-0.0.1-SNAPSHOT.jar"]

    depends_on: 
      maven-build:
        condition: service_completed_successfully
